development:
  adapter: postgresql
  database: school_tweet_dev
  encoding: utf8
  pool: 5

test:
  adapter: postgresql
  database: school_tweet_test
  encoding: utf8
  pool: 5

production:
  adapter: postgresql
  database: school_tweet
  username: some_tweets
  password: some_tweets
  encoding: utf8
  pool: 5
